on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: 1.11.x
            otp: 23.x
            check_formatted: true
            check_style: true
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: erlef/setup-elixir@v1.7
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get && mix deps.unlock --check-unused
      - name: Check formatting
        if: matrix.check_formatted
        run: mix format --check-formatted
      - name: Check style
        if: matrix.check_style
        run: mix credo --format flycheck
      - name: Compile project
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test  --cover
      - name: Retrieve PLT Cache
        uses: actions/cache@v2
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

      - name: Run dialyzer
        run: mix dialyzer --no-check --halt-exit-status
